export const challengeFactoryAbi = [
  {
    type: 'function',
    name: 'getChallengeCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getChallengesPaginated',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getActiveChallenges',
    inputs: [{ name: 'maxResults', type: 'uint256' }],
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getDefenderChallenges',
    inputs: [{ name: 'defender', type: 'address' }],
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolFeeBps',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minPrizePool',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minMessagePrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bountyListingFee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'oracle',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'challenges',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isChallenge',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createTournament',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'messagePrice', type: 'uint256' },
      { name: 'duration', type: 'uint256' },
      { name: 'secretHash', type: 'bytes32' },
      { name: 'model', type: 'string' },
    ],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'createBounty',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'duration', type: 'uint256' },
      { name: 'secretHash', type: 'bytes32' },
      { name: 'model', type: 'string' },
    ],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'createAlignment',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'rewardPerAttempt', type: 'uint256' },
      { name: 'duration', type: 'uint256' },
      { name: 'secretHash', type: 'bytes32' },
      { name: 'model', type: 'string' },
    ],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    type: 'event',
    name: 'ChallengeCreated',
    inputs: [
      { name: 'challenge', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'prizePool', type: 'uint256', indexed: false },
      { name: 'messagePrice', type: 'uint256', indexed: false },
      { name: 'name', type: 'string', indexed: false },
      { name: 'model', type: 'string', indexed: false },
      { name: 'challengeType', type: 'uint8', indexed: false },
    ],
  },
] as const

export const challengeAbi = [
  {
    type: 'function',
    name: 'defender',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'messagePrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'expiresAt',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'prizePool',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalAttempts',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'active',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'winner',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defenderEarnings',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'challengeType',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingWithdrawals',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'secretHash',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'timeRemaining',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCommit',
    inputs: [{ name: 'attacker', type: 'address' }],
    outputs: [
      { name: 'commitHash', type: 'bytes32' },
      { name: 'timestamp', type: 'uint256' },
      { name: 'revealed', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasValidCommit',
    inputs: [{ name: 'attacker', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAttackerAttempts',
    inputs: [{ name: 'attacker', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  // User-callable write functions
  {
    type: 'function',
    name: 'commitAttempt',
    inputs: [{ name: 'commitHash', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimExpiry',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // Events
  {
    type: 'event',
    name: 'AttackCommitted',
    inputs: [
      { name: 'attacker', type: 'address', indexed: true },
      { name: 'commitHash', type: 'bytes32', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ChallengeWon',
    inputs: [
      { name: 'attacker', type: 'address', indexed: true },
      { name: 'prize', type: 'uint256', indexed: false },
      { name: 'attemptNumber', type: 'uint256', indexed: false },
      { name: 'chatID', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ChallengeExpired',
    inputs: [
      { name: 'defender', type: 'address', indexed: true },
      { name: 'returnedAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Withdrawal',
    inputs: [
      { name: 'to', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
] as const

export const agentNFTAbi = [
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenOfOwnerByIndex',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSecurityScore',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'agents',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'challengeAddress', type: 'address' },
      { name: 'model', type: 'string' },
      { name: 'totalAttempts', type: 'uint256' },
      { name: 'attemptsSurvived', type: 'uint256' },
      { name: 'breached', type: 'bool' },
      { name: 'createdAt', type: 'uint256' },
      { name: 'resolvedAt', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAgent',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'challengeAddress', type: 'address' },
          { name: 'model', type: 'string' },
          { name: 'totalAttempts', type: 'uint256' },
          { name: 'attemptsSurvived', type: 'uint256' },
          { name: 'breached', type: 'bool' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'resolvedAt', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
] as const

export const reputationRegistryAbi = [
  {
    type: 'function',
    name: 'getAttackerReputation',
    inputs: [{ name: 'attacker', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'totalAttempts', type: 'uint256' },
          { name: 'successfulBreaches', type: 'uint256' },
          { name: 'challengesParticipated', type: 'uint256' },
          { name: 'totalEarnings', type: 'uint256' },
          { name: 'lastActiveAt', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getDefenderReputation',
    inputs: [{ name: 'defender', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'totalChallengesCreated', type: 'uint256' },
          { name: 'challengesSurvived', type: 'uint256' },
          { name: 'challengesBreached', type: 'uint256' },
          { name: 'totalPrizeDefended', type: 'uint256' },
          { name: 'totalPrizeLost', type: 'uint256' },
          { name: 'lastActiveAt', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAttackerScore',
    inputs: [{ name: 'attacker', type: 'address' }],
    outputs: [{ name: 'score', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getDefenderScore',
    inputs: [{ name: 'defender', type: 'address' }],
    outputs: [{ name: 'score', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const

export const oracleStakingAbi = [
  {
    type: 'function',
    name: 'getActiveOracles',
    inputs: [],
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOperator',
    inputs: [{ name: 'addr', type: 'address' }],
    outputs: [
      { name: 'stakedAmount', type: 'uint256' },
      { name: 'pendingUnstakeAmount', type: 'uint256' },
      { name: 'unstakeRequestedAt', type: 'uint256' },
      { name: 'rewards', type: 'uint256' },
      { name: 'isActive', type: 'bool' },
      { name: 'submitted', type: 'uint256' },
      { name: 'slashed', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minStake',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'activeOracleCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'confirmationsRequired',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const

export const erc20Abi = [
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowance',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transfer',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'decimals',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
  },
] as const
