/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestSuiteRouteImport } from './routes/test-suite'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AttestationsRouteImport } from './routes/attestations'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentRouteRouteImport } from './routes/agent/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as ChallengesCreateRouteImport } from './routes/challenges/create'
import { Route as ChallengesIdRouteImport } from './routes/challenges/$id'
import { Route as AgentTokenIdRouteImport } from './routes/agent/$tokenId'

const TestSuiteRoute = TestSuiteRouteImport.update({
  id: '/test-suite',
  path: '/test-suite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttestationsRoute = AttestationsRouteImport.update({
  id: '/attestations',
  path: '/attestations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRouteRoute = AgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRouteRoute,
} as any)
const ChallengesCreateRoute = ChallengesCreateRouteImport.update({
  id: '/challenges/create',
  path: '/challenges/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/challenges/$id',
  path: '/challenges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTokenIdRoute = AgentTokenIdRouteImport.update({
  id: '/$tokenId',
  path: '/$tokenId',
  getParentRoute: () => AgentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/attestations': typeof AttestationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/test-suite': typeof TestSuiteRoute
  '/agent/$tokenId': typeof AgentTokenIdRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/create': typeof ChallengesCreateRoute
  '/agent/': typeof AgentIndexRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attestations': typeof AttestationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/test-suite': typeof TestSuiteRoute
  '/agent/$tokenId': typeof AgentTokenIdRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/create': typeof ChallengesCreateRoute
  '/agent': typeof AgentIndexRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/attestations': typeof AttestationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/test-suite': typeof TestSuiteRoute
  '/agent/$tokenId': typeof AgentTokenIdRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/create': typeof ChallengesCreateRoute
  '/agent/': typeof AgentIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/analytics'
    | '/attestations'
    | '/leaderboard'
    | '/profile'
    | '/test-suite'
    | '/agent/$tokenId'
    | '/challenges/$id'
    | '/challenges/create'
    | '/agent/'
    | '/challenges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/attestations'
    | '/leaderboard'
    | '/profile'
    | '/test-suite'
    | '/agent/$tokenId'
    | '/challenges/$id'
    | '/challenges/create'
    | '/agent'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/analytics'
    | '/attestations'
    | '/leaderboard'
    | '/profile'
    | '/test-suite'
    | '/agent/$tokenId'
    | '/challenges/$id'
    | '/challenges/create'
    | '/agent/'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRouteRoute: typeof AgentRouteRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AttestationsRoute: typeof AttestationsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  TestSuiteRoute: typeof TestSuiteRoute
  ChallengesIdRoute: typeof ChallengesIdRoute
  ChallengesCreateRoute: typeof ChallengesCreateRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-suite': {
      id: '/test-suite'
      path: '/test-suite'
      fullPath: '/test-suite'
      preLoaderRoute: typeof TestSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attestations': {
      id: '/attestations'
      path: '/attestations'
      fullPath: '/attestations'
      preLoaderRoute: typeof AttestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/challenges/create': {
      id: '/challenges/create'
      path: '/challenges/create'
      fullPath: '/challenges/create'
      preLoaderRoute: typeof ChallengesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$tokenId': {
      id: '/agent/$tokenId'
      path: '/$tokenId'
      fullPath: '/agent/$tokenId'
      preLoaderRoute: typeof AgentTokenIdRouteImport
      parentRoute: typeof AgentRouteRoute
    }
  }
}

interface AgentRouteRouteChildren {
  AgentTokenIdRoute: typeof AgentTokenIdRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteRouteChildren: AgentRouteRouteChildren = {
  AgentTokenIdRoute: AgentTokenIdRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteRouteWithChildren = AgentRouteRoute._addFileChildren(
  AgentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRouteRoute: AgentRouteRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AttestationsRoute: AttestationsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  TestSuiteRoute: TestSuiteRoute,
  ChallengesIdRoute: ChallengesIdRoute,
  ChallengesCreateRoute: ChallengesCreateRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
